package com.tcn.exile.model;

public enum AgentState {
  UNSPECIFIED,
  IDLE,
  READY,
  PEERED,
  PAUSED,
  WRAPUP,
  PREPARING_PREVIEW,
  PREVIEWING,
  PREPARING_MANUAL,
  DIALING,
  INTERCOM,
  WARM_TRANSFER_PENDING,
  WARM_TRANSFER_ACTIVE,
  COLD_TRANSFER_ACTIVE,
  CONFERENCE_ACTIVE,
  LOGGED_OUT,
  SUSPENDED,
  EXTERNAL_TRANSFER,
  CALLBACK_SUSPENDED
}
