micronaut:
  control-panel:
    enabled: true
    allowed-environments: dev
  application:
    name: sati-demo
  views:
    dir: views
  router:
    static-resources:
      enabled: true
      css:
        mapping: /css/*.css
        paths: classpath:static/css
      images:
        mapping: /images/**
        paths: classpath:static/images
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8080

# Disable gRPC server health check since we don't need an embedded gRPC server
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    grpc:
      enabled: false

logger:
  levels:
    com.tcn.exile: DEBUG
    com.zaxxer.hikari: DEBUG
    io.micronaut.http.client: TRACE

http:
  server:
    enabled: true


# Enable single tenant mode
sati:
  tenant:
    type: single