micronaut:
  application:
    name: sati-demo-multi
    max-startup-time: 300s  # Increase startup timeout
  server:
    port: 8081
    
  # Enable scheduling explicitly
  scheduled:
    executor: scheduled
    
  # Enable health endpoints
  endpoints:
    health:
      enabled: true
      details-visible: ANONYMOUS
      sensitive: false
    routes:
      enabled: true
      sensitive: false
    beans:
      enabled: true
      sensitive: false
    info:
      enabled: true
      sensitive: false

# Logging configuration
logger:
  levels:
    # Set default log level
    root: INFO
    # Enable Micronaut debug logging
    io.micronaut: INFO
    io.micronaut.context: INFO
    io.micronaut.scheduling: DEBUG
    # Set multitenant-specific logging
    com.tcn.exile: DEBUG
    com.tcn.exile.multi: DEBUG
    com.tcn.exile.multi.config: DEBUG

# Enable multi tenant mode
sati:
  tenant:
    type: multi 